spring.datasource.url=
spring.datasource.username=admin
spring.datasource.password=thullo-app
spring.jpa.hibernate.ddl-auto=update
spring.security.oauth2.client.registration.google.client-id=5014057553-8gm9um6vnli3cle5rgigcdjpdrid14m9.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=tWZKVLxaD_ARWsriiiUFYoIk
spring.security.oauth2.client.registration.github.client-id=
spring.security.oauth2.client.registration.github.client-secret=
spring.security.oauth2.client.registration.facebook.client-id=836105467647403
spring.security.oauth2.client.registration.facebook.client-secret=720747de6a2517cac76fb1ab4b47c213
spring.security.oauth2.client.registration.twitter.client-id=N8KBmFP49zpe2GQz6s1Xk9u39
spring.security.oauth2.client.registration.twitter.client-secret=xGfkmgaelrTY1s1LA7zNel5tsbTPe9OfOSx7RibIzn0VdbKsaI
app.auth.tokenSecret=04ca023b39512e46d0c2cf4b48d5aac61d343848vvc87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb17833478cbcb
app.auth.tokenExpirationMsec=864000000
app.cors.allowedOrigins=https://thullo-web.netlify.app/
app.oauth2.authorizedRedirectUris=https://thullo-web.netlify.app/oauth2/redirect
spring.datasource.url=
spring.datasource.username=admin
spring.datasource.password=thullo-app
spring.jpa.hibernate.ddl-auto=update
spring.security.oauth2.client.registration.google.client-id=5014057553-8gm9um6vnli3cle5rgigcdjpdrid14m9.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=tWZKVLxaD_ARWsriiiUFYoIk
spring.security.oauth2.client.registration.github.client-id=
spring.security.oauth2.client.registration.github.client-secret=
spring.security.oauth2.client.registration.facebook.client-id=836105467647403
spring.security.oauth2.client.registration.facebook.client-secret=720747de6a2517cac76fb1ab4b47c213
spring.security.oauth2.client.registration.twitter.client-id=N8KBmFP49zpe2GQz6s1Xk9u39
spring.security.oauth2.client.registration.twitter.client-secret=xGfkmgaelrTY1s1LA7zNel5tsbTPe9OfOSx7RibIzn0VdbKsaI
app.auth.tokenSecret=04ca023b39512e46d0c2cf4b48d5aac61d343848vvc87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb17833478cbcb
app.auth.tokenExpirationMsec=864000000
app.cors.allowedOrigins=https://thullo-web.netlify.app/
app.oauth2.authorizedRedirectUris=https://thullo-web.netlify.app/oauth2/redirect
