ALREADY_SETUP: true
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/thullo"
    username: "root"
    password: "password"

  # JPA CONFIG
  jpa:
    hibernate:
      ddl-auto: update

  # OAUTH2 CONFIG
  security:
    oauth2:
      client:
        registration:

          google:
            client-id: 5014057553-8gm9um6vnli3cle5rgigcdjpdrid14m9.apps.googleusercontent.com
            client-secret: tWZKVLxaD_ARWsriiiUFYoIk
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

          github:
            client-id: 4f6a8f4bf80a0ce60af3
            client-secret: 444a4248745a395bb7ab0385a72b7358a96258cc
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user


          facebook:
            client-id: 836105467647403
            client-secret: 720747de6a2517cac76fb1ab4b47c213
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile

          twitter:
            client-id: N8KBmFP49zpe2GQz6s1Xk9u39
            client-secret: xGfkmgaelrTY1s1LA7zNel5tsbTPe9OfOSx7RibIzn0VdbKsaI
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            scope: tweet.read, users.read


        provider:

          twitter:
            authorizationUri: https://twitter.com/i/oauth2/authorize
            tokenUri: https://api.twitter.com/2/oauth2/token

          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)



app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d343848vvc87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 864000000
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - http://localhost:8080/oauth2/redirect


#  http://localhost:8080/oauth2/authorize/google?redirect_uri=http://localhost:8080/oauth2/redirect
#  http://localhost:8080/oauth2/authorize/github?redirect_uri=http://localhost:8080/oauth2/redirect
#  http://localhost:8080/oauth2/authorize/facebook?redirect_uri=http://localhost:8080/oauth2/redirect
#  http://localhost:8080/oauth2/authorize/twitter?redirect_uri=http://localhost:8080/oauth2/redirect
#
#
#url: "jdbc:mysql://thullo-db.cyjqopky4iiy.us-east-1.rds.amazonaws.com:3306/thullo"
  #    username: "admin"
  #    password: "thullo-app"

