spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${BD_PASSWORD}

  # JPA CONFIG
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL}


  # OAUTH2 CONFIG
  security:
    oauth2:
      client:
        registration:

          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user


          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile

          twitter:
            client-id: ${TWITTER_CLIENT_ID}
            client-secret: ${TWITTER_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            scope: tweet.read, users.read


        provider:

          twitter:
            authorizationUri: https://twitter.com/i/oauth2/authorize
            tokenUri: https://api.twitter.com/2/oauth2/token

          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)


app:
  auth:
    tokenSecret: ${JWT_TOKEN_SECRET}
    tokenExpirationMsec: ${JWT_EXPIRATION_TIME}
  cors:
    allowedOrigins: ${ORIGIN_1}
  oauth2:
    authorizedRedirectUris:
      - ${REDIRECT_URL_1}
      - ${REDIRECT_URL_2}



