name: Parse Database Configuration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


env:
  DB_URL: ${{ secrets.DB_URL }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  JPA_DDL: ${{ secrets.JPA_DDL }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  GITHUB_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
  GITHUB_CLIENT_SECRET: ${{ secrets.GH_CLIENT_SECRET }}
  FACEBOOK_CLIENT_ID: ${{ secrets.FACEBOOK_CLIENT_ID }}
  FACEBOOK_CLIENT_SECRET: ${{ secrets.FACEBOOK_CLIENT_SECRET }}
  TWITTER_CLIENT_ID: ${{ secrets.TWITTER_CLIENT_ID }}
  TWITTER_CLIENT_SECRET: ${{ secrets.TWITTER_CLIENT_SECRET }}
  JWT_TOKEN_SECRET: ${{ secrets.JWT_TOKEN_SECRET }}
  JWT_EXPIRATION_TIME: ${{ secrets.JWT_EXPIRATION_TIME }}
  ORIGINS: ${{ secrets.ORIGINS }}
  REDIRECT_URL: ${{ secrets.REDIRECT_URL }}


jobs:
  parse-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Delete existing database configuration
        run: |
          sed -i '/spring\.datasource\.url:/d' application-prod.yml
          sed -i '/spring\.datasource\.username:/d' application-prod.yml
          sed -i '/spring\.datasource\.password:/d' application-prod.yml
          sed -i '/spring\.jpa\.hibernate\.ddl-auto:/d' application-prod.yml
          sed -i '/spring\.security\.oauth2\.client\.registration\.google\.client-id:/d' application-prod.yml
          sed -i '/spring\.security\.oauth2\.client\.registration\.google\.client-secret:/d' application-prod.yml
          sed -i '/spring\.security\.oauth2\.client\.registration\.github\.client-id:/d' application-prod.yml
          sed -i '/spring\.security\.oauth2\.client\.registration\.github\.client-secret:/d' application-prod.yml
          sed -i '/spring\.security\.oauth2\.client\.registration\.facebook\.client-id:/d' application-prod.yml
          sed -i '/spring\.security\.oauth2\.client\.registration\.facebook\.client-secret:/d' application-prod.yml
          sed -i '/spring\.security\.oauth2\.client\.registration\.twitter\.client-id:/d' application-prod.yml
          sed -i '/spring\.security\.oauth2\.client\.registration\.twitter\.client-secret:/d' application-prod.yml
          sed -i '/app\.auth\.tokenSecret:/d' application-prod.yml
          sed -i '/app\.auth\.tokenExpirationMsec:/d' application-prod.yml
          sed -i '/app\.cors\.allowedOrigins:/d' application-prod.yml
          sed -i '/app\oauth2\.authorizedRedirectUris:/d' application-prod.yml

      - name: Replace properties in yml
        run: |
          echo "spring.datasource.url=$DB_URL" >> application-prod.yml
          echo "spring.datasource.username=$DB_USERNAME" >> application-prod.yml
          echo "spring.datasource.password=$DB_PASSWORD" >> application-prod.yml
          echo "spring.jpa.hibernate.ddl-auto=$JPA_DDL" >> application-prod.yml
          echo "spring.security.oauth2.client.registration.google.client-id=$GOOGLE_CLIENT_ID" >> application-prod.yml
          echo "spring.security.oauth2.client.registration.google.client-secret=$GOOGLE_CLIENT_SECRET" >> application-prod.yml
          echo "spring.security.oauth2.client.registration.github.client-id=$GH_CLIENT_ID" >> application-prod.yml
          echo "spring.security.oauth2.client.registration.github.client-secret=$GH_CLIENT_SECRET" >> application-prod.yml
          echo "spring.security.oauth2.client.registration.facebook.client-id=$FACEBOOK_CLIENT_ID" >> application-prod.yml
          echo "spring.security.oauth2.client.registration.facebook.client-secret=$FACEBOOK_CLIENT_SECRET" >> application-prod.yml
          echo "spring.security.oauth2.client.registration.twitter.client-id=$TWITTER_CLIENT_ID" >> application-prod.yml
          echo "spring.security.oauth2.client.registration.twitter.client-secret=$TWITTER_CLIENT_SECRET" >> application-prod.yml
          echo "app.auth.tokenSecret=$JWT_TOKEN_SECRET" >> application-prod.yml
          echo "app.auth.tokenExpirationMsec=$JWT_EXPIRATION_TIME" >> application-prod.yml
          echo "app.cors.allowedOrigins=$ORIGINS" >> application-prod.yml
          echo "app.oauth2.authorizedRedirectUris=$REDIRECT_URL" >> application-prod.yml

      - name: GitHub Commit & Push
        # You may pin to the exact commit or the version.
        # uses: actions-js/push@156f2b10c3aa000c44dbe75ea7018f32ae999772
        uses: actions-js/push@v1.4
        with:
          # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.GH_TOKEN }}
          # Email used to configure user.email in `git config`.
          author_email: ohida2001@gmailcom
          # Name used to configure user.name in `git config`.
          author_name: Ismail Abdullah

