name: Parse Database Configuration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


env:
  DB_URL: ${{ secrets.DB_URL }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  JPA_DDL: ${{ secrets.JPA_DDL }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  GITHUB_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
  GITHUB_CLIENT_SECRET: ${{ secrets.GH_CLIENT_SECRET }}
  FACEBOOK_CLIENT_ID: ${{ secrets.FACEBOOK_CLIENT_ID }}
  FACEBOOK_CLIENT_SECRET: ${{ secrets.FACEBOOK_CLIENT_SECRET }}
  TWITTER_CLIENT_ID: ${{ secrets.TWITTER_CLIENT_ID }}
  TWITTER_CLIENT_SECRET: ${{ secrets.TWITTER_CLIENT_SECRET }}
  JWT_TOKEN_SECRET: ${{ secrets.JWT_TOKEN_SECRET }}
  JWT_EXPIRATION_TIME: ${{ secrets.JWT_EXPIRATION_TIME }}
  ORIGINS: ${{ secrets.ORIGINS }}
  REDIRECT_URL: ${{ secrets.REDIRECT_URL }}


jobs:
  parse-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Replace properties in yml
        run: |
          grep -q  "spring.datasource.url=$DB_URL" >> application-prod.yml
          grep -q  "spring.datasource.username=$DB_USERNAME" >> application-prod.yml
          grep -q  "spring.datasource.password=$DB_PASSWORD" >> application-prod.yml
          grep -q  "spring.jpa.hibernate.ddl-auto=$JPA_DDL" >> application-prod.yml
          grep -q  "spring.security.oauth2.client.registration.google.client-id=$GOOGLE_CLIENT_ID" >> application-prod.yml
          grep -q  "spring.security.oauth2.client.registration.google.client-secret=$GOOGLE_CLIENT_SECRET" >> application-prod.yml
          grep -q  "spring.security.oauth2.client.registration.github.client-id=$GH_CLIENT_ID" >> application-prod.yml
          grep -q  "spring.security.oauth2.client.registration.github.client-secret=$GH_CLIENT_SECRET" >> application-prod.yml
          grep -q  "spring.security.oauth2.client.registration.facebook.client-id=$FACEBOOK_CLIENT_ID" >> application-prod.yml
          grep -q  "spring.security.oauth2.client.registration.facebook.client-secret=$FACEBOOK_CLIENT_SECRET" >> application-prod.yml
          grep -q  "spring.security.oauth2.client.registration.twitter.client-id=$TWITTER_CLIENT_ID" >> application-prod.yml
          grep -q  "spring.security.oauth2.client.registration.twitter.client-secret=$TWITTER_CLIENT_SECRET" >> application-prod.yml
          grep -q  "app.auth.tokenSecret=$JWT_TOKEN_SECRET" >> application-prod.yml
          grep -q  "app.auth.tokenExpirationMsec=$JWT_EXPIRATION_TIME" >> application-prod.yml
          grep -q  "app.cors.allowedOrigins=$ORIGINS" >> application-prod.yml
          grep -q  "app.oauth2.authorizedRedirectUris=$REDIRECT_URL" >> application-prod.yml

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update production configuration"
          branch: main